-
  branches:
    only:
      - master
  version: 1.0.{build}
  image: Visual Studio 2017
  build_script:
    - nuget restore ./ECMA2Yaml/ECMA2Yaml.sln
    - msbuild ./ECMA2Yaml/ECMA2Yaml.sln /p:Configuration=Release
    - %~dp0ECMA2Yaml/ECMA2Yaml/bin/Release/ECMA2Yaml.exe -s %~dp0test/xml -o %~dp0test/xml/yml_MREF_After -f
    - %~dp0ECMA2Yaml/ECMA2Yaml/bin/Release/ECMA2Yaml.exe -s %~dp0test/xml -o %~dp0test/xml/yml_SDP_After --SDP -f
    - %~dp0ECMA2Yaml/DiffFiles/bin/Release/DiffFiles.exe -o %~dp0test/yml_MREF -n %~dp0test/yml_MREF_After -l %~dp0test --Path
    - IF NOT %ErrorLevel% == 0 ECHO Exist different places for MREF yml
    - %~dp0ECMA2Yaml/DiffFiles/bin/Release/DiffFiles.exe -o %~dp0test/yml_SDP -n %~dp0test/yml_SDP_After -l %~dp0test --Path
    - IF NOT %ErrorLevel% == 0 ECHO Exist different places for SDP yml
  test: Auto
  on_success:
    - cd ECMA2Yaml
    - pack.bat %APPVEYOR_BUILD_VERSION%
    - IF NOT DEFINED APPVEYOR_PULL_REQUEST_NUMBER nuget push ./_nuget/Microsoft.DocAsCode.ECMA2Yaml.%APPVEYOR_BUILD_VERSION%.nupkg %opFeedKey% -Source %opFeedUrl%
    - IF NOT DEFINED APPVEYOR_PULL_REQUEST_NUMBER nuget push ./_nuget/Microsoft.DocAsCode.ECMAHelper.%APPVEYOR_BUILD_VERSION%.nupkg %opFeedKey% -Source %opFeedUrl%
    - IF NOT DEFINED APPVEYOR_PULL_REQUEST_NUMBER nuget push ./_nuget/Microsoft.DocAsCode.ECMA2Yaml.%APPVEYOR_BUILD_VERSION%.nupkg %nugetKey% -Source %nugetUrl%
    - IF NOT DEFINED APPVEYOR_PULL_REQUEST_NUMBER nuget push ./_nuget/Microsoft.DocAsCode.ECMAHelper.%APPVEYOR_BUILD_VERSION%.nupkg %nugetKey% -Source %nugetUrl%
-
  branches:
    only:
      - develop
  version: 1.0.{build}-alpha
  image: Visual Studio 2017
  build_script:
    - nuget restore ./ECMA2Yaml/ECMA2Yaml.sln
    - msbuild ./ECMA2Yaml/ECMA2Yaml.sln /p:Configuration=Release
  test: Auto
  on_success:
    - cd ECMA2Yaml
    - pack.bat %APPVEYOR_BUILD_VERSION%
    - IF NOT DEFINED APPVEYOR_PULL_REQUEST_NUMBER nuget push ./_nuget/Microsoft.DocAsCode.ECMA2Yaml.%APPVEYOR_BUILD_VERSION%.nupkg %opFeedKey% -Source %opDevFeedUrl%
    - IF NOT DEFINED APPVEYOR_PULL_REQUEST_NUMBER nuget push ./_nuget/Microsoft.DocAsCode.ECMAHelper.%APPVEYOR_BUILD_VERSION%.nupkg %opFeedKey% -Source %opDevFeedUrl%
    - IF NOT DEFINED APPVEYOR_PULL_REQUEST_NUMBER nuget push ./_nuget/Microsoft.DocAsCode.ECMA2Yaml.%APPVEYOR_BUILD_VERSION%.nupkg %nugetKey% -Source %nugetUrl%
    - IF NOT DEFINED APPVEYOR_PULL_REQUEST_NUMBER nuget push ./_nuget/Microsoft.DocAsCode.ECMAHelper.%APPVEYOR_BUILD_VERSION%.nupkg %nugetKey% -Source %nugetUrl%
