version: 1.0.{build}
image: Visual Studio 2015
build_script:
  - nuget restore ./ECMA2Yaml/ECMA2Yaml.sln
  - msbuild ./ECMA2Yaml/ECMA2Yaml.sln /p:Configuration=Release
test: off
on_success:
  - pushd ECMA2Yaml
  - pack.bat 1.0.{build}
  - nuget push ./_nuget/Microsoft.DocAsCode.ECMA2Yaml.1.0.{build}.nupkg %mygetKey% -Source %mygetUrl%
  - nuget push ./_nuget/Microsoft.DocAsCode.ECMAHelper.1.0.{build}.nupkg %mygetKey% -Source %mygetUrl%
  - popd