version: 1.0.{build}
branches:
  only:
    - master
    - develop
environment:
  MYGETFEED: $(opFeedUrl)
  docsNugetFeed: $(docsProdNugetUrl)
image: Visual Studio 2019
build_script:
- echo %APPVEYOR_BUILD_VERSION%
- echo %MYGETFEED%
- nuget restore ./ECMA2Yaml/ECMA2Yaml.sln
- msbuild ./ECMA2Yaml/ECMA2Yaml.sln /p:Configuration=Release
- diffYaml.bat
- diffIntellisense.bat
test: Auto
on_success:
- cd ECMA2Yaml
- pack.bat %APPVEYOR_BUILD_VERSION%
- nugetPush.bat

for:
-
  branches:
    only:
      - develop
  version: 1.0.{build}-alpha
  environment:
    MYGETFEED: $(opDevFeedUrl)
    docsNugetFeed: $(docsPPENugetUrl)