trigger:
- master
- develop

pr:
- develop
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: BatchScript@1
  inputs:
    filename: 'diffYaml.bat'

- task: BatchScript@1
  inputs:
    filename: 'diffIntellisense.bat'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"
      
      if ($(Build.Reason) -eq "PullRequest" -or $env:BUILD_SOURCEBRANCH -eq 'refs/heads/develop') {
          Write-Host "prerelease"
      }
      else if ($(Build.Reason) -eq "Manual" -or $(Build.Reason) -eq "IndividualCI") {
          Write-Host "release"
      }